// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nfAA-NgIzNzgqZwpTkxynF1l1WzP0aw',
    appId: '1:969989049512:web:eb57e40a42610ff18b069d',
    messagingSenderId: '969989049512',
    projectId: 'loginsafdfdsa',
    authDomain: 'loginsafdfdsa.firebaseapp.com',
    storageBucket: 'loginsafdfdsa.appspot.com',
    measurementId: 'G-PPB8KGGS61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA_x1g1iKgjvN9UMweN4ImXRb3Tb53HuA',
    appId: '1:969989049512:android:cb140eeb96d84c498b069d',
    messagingSenderId: '969989049512',
    projectId: 'loginsafdfdsa',
    storageBucket: 'loginsafdfdsa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByrP270mwvLddRdEqRObvbNBRdsoHfRm4',
    appId: '1:969989049512:ios:849884741e7159ee8b069d',
    messagingSenderId: '969989049512',
    projectId: 'loginsafdfdsa',
    storageBucket: 'loginsafdfdsa.appspot.com',
    iosClientId: '969989049512-suatbqc1df3babph9nno8a523ipi97on.apps.googleusercontent.com',
    iosBundleId: 'com.example.backing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByrP270mwvLddRdEqRObvbNBRdsoHfRm4',
    appId: '1:969989049512:ios:849884741e7159ee8b069d',
    messagingSenderId: '969989049512',
    projectId: 'loginsafdfdsa',
    storageBucket: 'loginsafdfdsa.appspot.com',
    iosClientId: '969989049512-suatbqc1df3babph9nno8a523ipi97on.apps.googleusercontent.com',
    iosBundleId: 'com.example.backing',
  );
}
